### ISSUE TITLE
delete this repo

### ISSUE THREAD

**Issue by squat** [observatorium/receive-proxy#2]
cc @observatorium/maintainers 

This repository only holds code to build an NGINX container and the container does not include any NGINX configuration so there is no logic anywhere that is related to Obsrevatorium or Thanos Receive/Prometheus Remote Write. I don't think this repository brings value to the Observatorium project beyond what an upstream `nginx` container on Docker Hub provides.

I propose deleting this repository as it does not seem relevant to the Observatorium project. Perhaps this repository is used to build an NGINX container for Red Hat's infrastructure? In that case, I'd suggest moving this out of the Observatorium org and perhaps giving it to rhobs.

**Comment by kakkoyun** [comment]
+1 to moving. Thanks for raising the issue.

**Comment by matej-g** [comment]
Agreed, this does not add anything to Observatorium project and has not really been updated in over 2 years. On our (Red Hat) side we should be fine with deleting this (we have forks just in case), also cc @spaparaju.

**Comment by PhilipGough** [comment]
@squat - just to follow up we (RH) have updated to use the s2i image in place of this for several weeks, so there is no issue with deleting this now on our side.

**Comment by squat** [comment]
Ack deleting this now!
